version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file:
      - ./mise/env/base.env
    environment:
      RAILS_ENV: development

  db:
    image: postgres:13.5
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./mise/env/base.env


volumes:
  db_data:
  gem_cache:
  node_modules: